const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
const error=(message,status=400)=>json({error:message},status);
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
const productSelect=`SELECT id, reference, name, category, set_name AS setName, card_number AS cardNumber,
  language, condition, notes, price, status, front_image_key AS frontImageKey,
  back_image_key AS backImageKey, created_at AS createdAt, updated_at AS updatedAt
  FROM products`;
function imageUrl(request,key){return key?`${new URL(request.url).origin}/api/images/${encodeURIComponent(key)}`:null}
function present(request,row){const frontImageUrl=imageUrl(request,row.frontImageKey),backImageUrl=imageUrl(request,row.backImageKey);return {...row,set:row.setName,image:frontImageUrl,imageAlt:`Front photograph of ${row.name}`,frontImageUrl,backImageUrl}}
function adminIdentity(request,env){const email=clean(request.headers.get("CF-Access-Authenticated-User-Email"),254).toLowerCase();if(!email)return null;const allowed=clean(env.ADMIN_EMAILS,2000).toLowerCase().split(",").map((v)=>v.trim()).filter(Boolean);return !allowed.length||allowed.includes(email)?email:null}
function validateProduct(input){const product={reference:clean(input.reference,30).toUpperCase(),name:clean(input.name,120),category:clean(input.category,60),setName:clean(input.setName,100),cardNumber:clean(input.cardNumber,40),language:clean(input.language,30),condition:clean(input.condition,40),notes:clean(input.notes,500),price:Number(input.price),status:clean(input.status,20).toLowerCase(),frontImageKey:input.frontImageKey?clean(input.frontImageKey,240):null,backImageKey:input.backImageKey?clean(input.backImageKey,240):null};if(!product.reference||!product.name||!product.category)return {error:"Reference, product name and category are required."};if(!Number.isFinite(product.price)||product.price<0)return {error:"Enter a valid non-negative price."};if(!["draft","available","claimed","sold","archived"].includes(product.status))return {error:"Invalid inventory status."};return {product}}
async function publicProducts(request,env){const result=await env.DB.prepare(`${productSelect} WHERE status = 'available' ORDER BY updated_at DESC, id DESC`).all();const lastUpdated=result.results[0]?.updatedAt||"";return json({lastUpdated,products:result.results.map((row)=>present(request,row))},200,{"cache-control":"public, max-age=30"})}
async function adminProducts(request,env,email){const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all();return json({adminEmail:email,products:result.results.map((row)=>present(request,row))})}
async function saveProduct(request,env,id=null){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const checked=validateProduct(body);if(checked.error)return error(checked.error);const p=checked.product;try{if(id){const result=await env.DB.prepare(`UPDATE products SET reference=?,name=?,category=?,set_name=?,card_number=?,language=?,condition=?,notes=?,price=?,status=?,front_image_key=?,back_image_key=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageKey,p.backImageKey,id).run();if(!result.meta.changes)return error("Product not found.",404);return json({id:Number(id),message:"Product updated."})}const result=await env.DB.prepare(`INSERT INTO products (reference,name,category,set_name,card_number,language,condition,notes,price,status,front_image_key,back_image_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageKey,p.backImageKey).run();return json({id:result.meta.last_row_id,message:"Product created."},201)}catch(cause){if(String(cause).includes("UNIQUE"))return error("That reference is already in use.",409);throw cause}}
async function uploadImage(request,env){const form=await request.formData(),file=form.get("image"),reference=clean(form.get("reference"),30).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")||"product",side=clean(form.get("side"),10)==="back"?"back":"front";if(!(file instanceof File)||!file.size)return error("Choose an image to upload.");if(file.size>8*1024*1024)return error("Image must be 8 MB or smaller.",413);const extensions={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"},extension=extensions[file.type];if(!extension)return error("Use a JPG, PNG or WebP image.",415);const key=`products/${reference}/${side}-${crypto.randomUUID()}.${extension}`;await env.PRODUCT_IMAGES.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}});return json({key,url:imageUrl(request,key)},201)}
async function serveImage(request,env,key){const object=await env.PRODUCT_IMAGES.get(key);if(!object)return new Response("Not found",{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set("etag",object.httpEtag);headers.set("cache-control","public, max-age=31536000, immutable");return new Response(object.body,{headers})}
export async function onRequest(context){const {request,env,params}=context;try{if(!env.DB)return error("D1 binding DB is missing.",503);const path=Array.isArray(params.path)?params.path.join("/"):String(params.path||"");if(request.method==="GET"&&path==="products")return publicProducts(request,env);if(request.method==="GET"&&path.startsWith("images/")){if(!env.PRODUCT_IMAGES)return error("R2 binding PRODUCT_IMAGES is missing.",503);return serveImage(request,env,decodeURIComponent(path.slice(7)))}const email=adminIdentity(request,env);if(!email)return error("Administrator access required.",401);if(request.method==="GET"&&path==="admin/products")return adminProducts(request,env,email);if(request.method==="POST"&&path==="admin/products")return saveProduct(request,env);const match=path.match(/^admin\/products\/(\d+)$/);if(match&&request.method==="PUT")return saveProduct(request,env,match[1]);if(match&&request.method==="DELETE"){const result=await env.DB.prepare("UPDATE products SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(match[1]).run();return result.meta.changes?json({message:"Product archived."}):error("Product not found.",404)}if(request.method==="POST"&&path==="admin/images"){if(!env.PRODUCT_IMAGES)return error("R2 binding PRODUCT_IMAGES is missing.",503);return uploadImage(request,env)}return error("Not found.",404)}catch(cause){console.error(cause);return error("Unexpected server error.",500)}}
