const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
const error=(message,status=400)=>json({error:message},status);
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
const productSelect=`SELECT id, reference, name, category, set_name AS setName, card_number AS cardNumber,
  language, condition, notes, price, status, front_image_url AS frontImageUrl,
  back_image_url AS backImageUrl, created_at AS createdAt, updated_at AS updatedAt
  FROM products`;
function present(request,row){return {...row,set:row.setName,image:row.frontImageUrl,imageAlt:`Front photograph of ${row.name}`}}
function adminIdentity(request,env){const email=clean(request.headers.get("CF-Access-Authenticated-User-Email"),254).toLowerCase();if(!email)return null;const allowed=clean(env.ADMIN_EMAILS,2000).toLowerCase().split(",").map((v)=>v.trim()).filter(Boolean);return !allowed.length||allowed.includes(email)?email:null}
function validImageUrl(value){if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"?url.href:null}catch{return null}}
function validateProduct(input){const rawFront=clean(input.frontImageUrl,1000),rawBack=clean(input.backImageUrl,1000);const product={reference:clean(input.reference,30).toUpperCase(),name:clean(input.name,120),category:clean(input.category,60),setName:clean(input.setName,100),cardNumber:clean(input.cardNumber,40),language:clean(input.language,30),condition:clean(input.condition,40),notes:clean(input.notes,500),price:Number(input.price),status:clean(input.status,20).toLowerCase(),frontImageUrl:validImageUrl(rawFront),backImageUrl:validImageUrl(rawBack)};if(!product.reference||!product.name||!product.category)return {error:"Reference, product name and category are required."};if(rawFront&&!product.frontImageUrl||rawBack&&!product.backImageUrl)return {error:"Photograph addresses must be valid HTTPS URLs."};if(!Number.isFinite(product.price)||product.price<0)return {error:"Enter a valid non-negative price."};if(!["draft","available","claimed","sold","archived"].includes(product.status))return {error:"Invalid inventory status."};return {product}}
async function publicProducts(request,env){const result=await env.DB.prepare(`${productSelect} WHERE status = 'available' ORDER BY updated_at DESC, id DESC`).all();const lastUpdated=result.results[0]?.updatedAt||"";return json({lastUpdated,products:result.results.map((row)=>present(request,row))},200,{"cache-control":"public, max-age=30"})}
async function adminProducts(request,env,email){const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all();return json({adminEmail:email,products:result.results.map((row)=>present(request,row))})}
async function saveProduct(request,env,id=null){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const checked=validateProduct(body);if(checked.error)return error(checked.error);const p=checked.product;try{if(id){const result=await env.DB.prepare(`UPDATE products SET reference=?,name=?,category=?,set_name=?,card_number=?,language=?,condition=?,notes=?,price=?,status=?,front_image_url=?,back_image_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageUrl,p.backImageUrl,id).run();if(!result.meta.changes)return error("Product not found.",404);return json({id:Number(id),message:"Product updated."})}const result=await env.DB.prepare(`INSERT INTO products (reference,name,category,set_name,card_number,language,condition,notes,price,status,front_image_url,back_image_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageUrl,p.backImageUrl).run();return json({id:result.meta.last_row_id,message:"Product created."},201)}catch(cause){if(String(cause).includes("UNIQUE"))return error("That reference is already in use.",409);throw cause}}
export async function onRequest(context){const {request,env,params}=context;try{if(!env.DB)return error("D1 binding DB is missing.",503);const path=Array.isArray(params.path)?params.path.join("/"):String(params.path||"");if(request.method==="GET"&&path==="products")return publicProducts(request,env);const email=adminIdentity(request,env);if(!email)return error("Administrator access required.",401);if(request.method==="GET"&&path==="admin/products")return adminProducts(request,env,email);if(request.method==="POST"&&path==="admin/products")return saveProduct(request,env);const match=path.match(/^admin\/products\/(\d+)$/);if(match&&request.method==="PUT")return saveProduct(request,env,match[1]);if(match&&request.method==="DELETE"){const result=await env.DB.prepare("UPDATE products SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(match[1]).run();return result.meta.changes?json({message:"Product archived."}):error("Product not found.",404)}return error("Not found.",404)}catch(cause){console.error(cause);return error("Unexpected server error.",500)}}
