const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
const error=(message,status=400)=>json({error:message},status);
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
const SESSION_COOKIE="__Host-kz_admin_session";
const SESSION_SECONDS=7*24*60*60;
const productSelect=`SELECT id, reference, name, category, set_name AS setName, card_number AS cardNumber,
  language, condition, notes, price, status, front_image_url AS frontImageUrl,
  back_image_url AS backImageUrl, created_at AS createdAt, updated_at AS updatedAt
  FROM products`;
function present(request,row){return {...row,set:row.setName,image:row.frontImageUrl,imageAlt:`Front photograph of ${row.name}`}}
const textEncoder=new TextEncoder();
function encodeUrlSafe(value){return btoa(value).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function decodeUrlSafe(value){const normal=value.replace(/-/g,"+").replace(/_/g,"/");return atob(normal+"=".repeat((4-normal.length%4)%4))}
async function signature(value,secret){const key=await crypto.subtle.importKey("raw",textEncoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return encodeUrlSafe(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign("HMAC",key,textEncoder.encode(value)))))}
async function constantTimeMatch(candidate,expected){const [left,right]=await Promise.all([candidate,expected].map((value)=>crypto.subtle.digest("SHA-256",textEncoder.encode(String(value)))));const leftBytes=new Uint8Array(left),rightBytes=new Uint8Array(right);let difference=0;for(let index=0;index<leftBytes.length;index++)difference|=leftBytes[index]^rightBytes[index];return difference===0}
function cookieValue(request,name){const cookies=request.headers.get("Cookie")||"";for(const part of cookies.split(";")){const [key,...value]=part.trim().split("=");if(key===name)return value.join("=")}return null}
async function createSession(secret){const payload=encodeUrlSafe(JSON.stringify({exp:Math.floor(Date.now()/1000)+SESSION_SECONDS}));return `${payload}.${await signature(payload,secret)}`}
async function hasAdminSession(request,env){const secret=String(env.ADMIN_PASSWORD??""),token=cookieValue(request,SESSION_COOKIE);if(!secret||!token)return false;const [payload,providedSignature,...extra]=token.split(".");if(!payload||!providedSignature||extra.length)return false;try{const expectedSignature=await signature(payload,secret);if(!await constantTimeMatch(providedSignature,expectedSignature))return false;const session=JSON.parse(decodeUrlSafe(payload));return Number.isFinite(session.exp)&&session.exp>Math.floor(Date.now()/1000)}catch{return false}}
function sessionCookie(value,maxAge=SESSION_SECONDS){return `${SESSION_COOKIE}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`}
function sameOrigin(request){const origin=request.headers.get("Origin");return Boolean(origin)&&origin===new URL(request.url).origin}
async function login(request,env){if(!env.ADMIN_PASSWORD)return error("Administrator password is not configured.",503);if(!sameOrigin(request))return error("Invalid login request.",403);let body;try{body=await request.json()}catch{return error("Invalid login request.")};if(!await constantTimeMatch(body.password,env.ADMIN_PASSWORD))return error("Incorrect password.",401);if(!env.DB)return error("D1 binding DB is missing.",503);const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all(),session=await createSession(env.ADMIN_PASSWORD);return json({message:"Signed in.",adminName:"Administrator",products:result.results.map((row)=>present(request,row))},200,{"set-cookie":sessionCookie(session)})}
function logout(){return json({message:"Signed out."},200,{"set-cookie":sessionCookie("",0)})}
function validImageUrl(value){if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"?url.href:null}catch{return null}}
function validateProduct(input){const rawFront=clean(input.frontImageUrl,1000),rawBack=clean(input.backImageUrl,1000);const product={reference:clean(input.reference,30).toUpperCase(),name:clean(input.name,120),category:clean(input.category,60),setName:clean(input.setName,100),cardNumber:clean(input.cardNumber,40),language:clean(input.language,30),condition:clean(input.condition,40),notes:clean(input.notes,500),price:Number(input.price),status:clean(input.status,20).toLowerCase(),frontImageUrl:validImageUrl(rawFront),backImageUrl:validImageUrl(rawBack)};if(!product.reference||!product.name||!product.category)return {error:"Reference, product name and category are required."};if(rawFront&&!product.frontImageUrl||rawBack&&!product.backImageUrl)return {error:"Photograph addresses must be valid HTTPS URLs."};if(!Number.isFinite(product.price)||product.price<0)return {error:"Enter a valid non-negative price."};if(!["draft","available","claimed","sold","archived"].includes(product.status))return {error:"Invalid inventory status."};return {product}}
async function publicProducts(request,env){const result=await env.DB.prepare(`${productSelect} WHERE status = 'available' ORDER BY updated_at DESC, id DESC`).all();const lastUpdated=result.results[0]?.updatedAt||"";return json({lastUpdated,products:result.results.map((row)=>present(request,row))},200,{"cache-control":"public, max-age=30"})}
async function adminProducts(request,env){const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all();return json({adminName:"Administrator",products:result.results.map((row)=>present(request,row))})}
async function saveProduct(request,env,id=null){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const checked=validateProduct(body);if(checked.error)return error(checked.error);const p=checked.product;try{if(id){const result=await env.DB.prepare(`UPDATE products SET reference=?,name=?,category=?,set_name=?,card_number=?,language=?,condition=?,notes=?,price=?,status=?,front_image_url=?,back_image_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageUrl,p.backImageUrl,id).run();if(!result.meta.changes)return error("Product not found.",404);return json({id:Number(id),message:"Product updated."})}const result=await env.DB.prepare(`INSERT INTO products (reference,name,category,set_name,card_number,language,condition,notes,price,status,front_image_url,back_image_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.status,p.frontImageUrl,p.backImageUrl).run();return json({id:result.meta.last_row_id,message:"Product created."},201)}catch(cause){if(String(cause).includes("UNIQUE"))return error("That reference is already in use.",409);throw cause}}
function encodeBase64(buffer){const bytes=new Uint8Array(buffer),chunk=0x8000,parts=[];for(let index=0;index<bytes.length;index+=chunk)parts.push(String.fromCharCode(...bytes.subarray(index,index+chunk)));return btoa(parts.join(""))}
async function uploadImage(request,env){if(!env.GITHUB_TOKEN)return error("GitHub image upload is not configured.",503);const form=await request.formData(),file=form.get("image"),reference=clean(form.get("reference"),30).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")||"product",side=clean(form.get("side"),10)==="back"?"back":"front";if(!(file instanceof File)||!file.size)return error("Choose an image to upload.");if(file.size>4*1024*1024)return error("Image must be 4 MB or smaller.",413);const extensions={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"},extension=extensions[file.type];if(!extension)return error("Use a JPG, PNG or WebP image.",415);const repository=clean(env.GITHUB_REPOSITORY||"kollectozam/kollectozamkollectables",200),branch=clean(env.GITHUB_BRANCH||"main",100),filename=`${side}-${Date.now()}-${crypto.randomUUID().slice(0,8)}.${extension}`,path=`frontend/assets/img/products/${reference}/${filename}`,endpoint=`https://api.github.com/repos/${repository}/contents/${path}`;const response=await fetch(endpoint,{method:"PUT",headers:{"authorization":`Bearer ${env.GITHUB_TOKEN}`,"accept":"application/vnd.github+json","content-type":"application/json","user-agent":"kollectozam-admin","x-github-api-version":"2022-11-28"},body:JSON.stringify({message:`Add ${reference} ${side} product image`,content:encodeBase64(await file.arrayBuffer()),branch})});const result=await response.json().catch(()=>({}));if(!response.ok){console.error("GitHub upload failed",response.status,result?.message);return error(response.status===401||response.status===403?"GitHub upload permission was rejected.":"Photograph upload failed.",502)}return json({url:result.content?.download_url,path:result.content?.path},201)}
export async function onRequest(context){const {request,env,params}=context;try{const path=Array.isArray(params.path)?params.path.join("/"):String(params.path||"");if(request.method==="GET"&&path==="health")return json({ok:true,databaseBound:Boolean(env.DB)});if(request.method==="POST"&&path==="admin/login")return login(request,env);if(request.method==="POST"&&path==="admin/logout"){if(!sameOrigin(request))return error("Invalid logout request.",403);return logout()}if(request.method==="GET"&&path==="products"){if(!env.DB)return error("D1 binding DB is missing.",503);return publicProducts(request,env)}if(!path.startsWith("admin/"))return error("Not found.",404);if(!await hasAdminSession(request,env))return error("Administrator sign-in required.",401);if(request.method!=="GET"&&!sameOrigin(request))return error("Invalid administrator request.",403);if(!env.DB)return error("D1 binding DB is missing.",503);if(request.method==="GET"&&path==="admin/session")return json({authenticated:true,adminName:"Administrator"});if(request.method==="GET"&&path==="admin/products")return adminProducts(request,env);if(request.method==="POST"&&path==="admin/products")return saveProduct(request,env);if(request.method==="POST"&&path==="admin/images")return uploadImage(request,env);const match=path.match(/^admin\/products\/(\d+)$/);if(match&&request.method==="PUT")return saveProduct(request,env,match[1]);if(match&&request.method==="DELETE"){const result=await env.DB.prepare("UPDATE products SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(match[1]).run();return result.meta.changes?json({message:"Product archived."}):error("Product not found.",404)}return error("Not found.",404)}catch(cause){console.error(cause);const message=String(cause&&cause.message||cause||"");return error(message.includes("no such table")?"The D1 products table has not been created.":message.includes("no such column")?"The D1 products table schema is outdated.":"Unexpected server error.",500)}}
