const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
const error=(message,status=400)=>json({error:message},status);
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
const SESSION_COOKIE="__Host-kz_admin_session";
const SESSION_SECONDS=7*24*60*60;
const productSelect=`SELECT id, reference, name, category, set_name AS setName, card_number AS cardNumber,
  language, condition, notes, price, quantity, status, front_image_url AS frontImageUrl,
  back_image_url AS backImageUrl, created_at AS createdAt, updated_at AS updatedAt
  FROM products`;
let schemaReady=null;
// Idempotent upgrade (mirrors migrations/0003_quick_add.sql) so a missed manual migration cannot break the site.
async function ensureSchema(env){if(!schemaReady)schemaReady=(async()=>{try{await env.DB.prepare("ALTER TABLE products ADD COLUMN quantity INTEGER NOT NULL DEFAULT 1").run()}catch(cause){if(!String(cause).includes("duplicate column"))throw cause}await env.DB.prepare("CREATE TABLE IF NOT EXISTS set_names (lang TEXT NOT NULL, set_id TEXT NOT NULL, display_name TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (lang, set_id))").run();await env.DB.prepare("CREATE TABLE IF NOT EXISTS lookup_cache (key TEXT PRIMARY KEY, body TEXT NOT NULL, fetched_at INTEGER NOT NULL)").run()})().catch((cause)=>{schemaReady=null;throw cause});return schemaReady}
async function nextReferenceNumber(env){const row=await env.DB.prepare("SELECT MAX(CAST(SUBSTR(reference,4) AS INTEGER)) AS top FROM products WHERE reference LIKE 'KZ-%'").first();return (Number(row?.top)||0)+1}
const formatReference=(number)=>`KZ-${String(number).padStart(3,"0")}`;
// D1 CURRENT_TIMESTAMP is UTC without a zone marker ("2026-09-26 08:00:00"); browsers would read it as local time.
const utcIso=(value)=>/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(String(value??""))?`${value.replace(" ","T")}Z`:value;
function present(request,row){return {...row,createdAt:utcIso(row.createdAt),updatedAt:utcIso(row.updatedAt),set:row.setName,image:row.frontImageUrl,imageAlt:`Front photograph of ${row.name}`}}
const textEncoder=new TextEncoder();
function encodeUrlSafe(value){return btoa(value).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function decodeUrlSafe(value){const normal=value.replace(/-/g,"+").replace(/_/g,"/");return atob(normal+"=".repeat((4-normal.length%4)%4))}
async function signature(value,secret){const key=await crypto.subtle.importKey("raw",textEncoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return encodeUrlSafe(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign("HMAC",key,textEncoder.encode(value)))))}
async function constantTimeMatch(candidate,expected){const [left,right]=await Promise.all([candidate,expected].map((value)=>crypto.subtle.digest("SHA-256",textEncoder.encode(String(value)))));const leftBytes=new Uint8Array(left),rightBytes=new Uint8Array(right);let difference=0;for(let index=0;index<leftBytes.length;index++)difference|=leftBytes[index]^rightBytes[index];return difference===0}
function cookieValue(request,name){const cookies=request.headers.get("Cookie")||"";for(const part of cookies.split(";")){const [key,...value]=part.trim().split("=");if(key===name)return value.join("=")}return null}
async function createSession(secret){const payload=encodeUrlSafe(JSON.stringify({exp:Math.floor(Date.now()/1000)+SESSION_SECONDS}));return `${payload}.${await signature(payload,secret)}`}
async function hasAdminSession(request,env){const secret=String(env.ADMIN_PASSWORD??""),token=cookieValue(request,SESSION_COOKIE);if(!secret||!token)return false;const [payload,providedSignature,...extra]=token.split(".");if(!payload||!providedSignature||extra.length)return false;try{const expectedSignature=await signature(payload,secret);if(!await constantTimeMatch(providedSignature,expectedSignature))return false;const session=JSON.parse(decodeUrlSafe(payload));return Number.isFinite(session.exp)&&session.exp>Math.floor(Date.now()/1000)}catch{return false}}
function sessionCookie(value,maxAge=SESSION_SECONDS){return `${SESSION_COOKIE}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`}
function sameOrigin(request){const origin=request.headers.get("Origin");return Boolean(origin)&&origin===new URL(request.url).origin}
async function login(request,env){if(!env.ADMIN_PASSWORD)return error("Administrator password is not configured.",503);if(!sameOrigin(request))return error("Invalid login request.",403);let body;try{body=await request.json()}catch{return error("Invalid login request.")};if(!await constantTimeMatch(body.password,env.ADMIN_PASSWORD))return error("Incorrect password.",401);if(!env.DB)return error("D1 binding DB is missing.",503);await ensureSchema(env);const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all(),session=await createSession(env.ADMIN_PASSWORD);return json({message:"Signed in.",adminName:"Administrator",products:result.results.map((row)=>present(request,row))},200,{"set-cookie":sessionCookie(session)})}
function logout(){return json({message:"Signed out."},200,{"set-cookie":sessionCookie("",0)})}
function validImageUrl(value){if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"?url.href:null}catch{return null}}
function validateProduct(input){const rawFront=clean(input.frontImageUrl,1000),rawBack=clean(input.backImageUrl,1000);const product={reference:clean(input.reference,30).toUpperCase(),name:clean(input.name,120),category:clean(input.category,60),setName:clean(input.setName,100),cardNumber:clean(input.cardNumber,40),language:clean(input.language,30),condition:clean(input.condition,40),notes:clean(input.notes,500),price:Number(input.price),quantity:Number(input.quantity??1),status:clean(input.status,20).toLowerCase(),frontImageUrl:validImageUrl(rawFront),backImageUrl:validImageUrl(rawBack)};if(!product.name||!product.category)return {error:"Product name and category are required."};if(!Number.isInteger(product.quantity)||product.quantity<1||product.quantity>99)return {error:"Quantity must be a whole number from 1 to 99."};if(rawFront&&!product.frontImageUrl||rawBack&&!product.backImageUrl)return {error:"Photograph addresses must be valid HTTPS URLs."};if(!Number.isFinite(product.price)||product.price<0)return {error:"Enter a valid non-negative price."};if(!["draft","available","claimed","sold","archived"].includes(product.status))return {error:"Invalid inventory status."};return {product}}
async function publicProducts(request,env){const result=await env.DB.prepare(`${productSelect} WHERE status = 'available' ORDER BY updated_at DESC, id DESC`).all();const lastUpdated=utcIso(result.results[0]?.updatedAt)||"";return json({lastUpdated,products:result.results.map((row)=>present(request,row))},200,{"cache-control":"public, max-age=30"})}
async function adminProducts(request,env){const result=await env.DB.prepare(`${productSelect} ORDER BY updated_at DESC, id DESC`).all();return json({adminName:"Administrator",products:result.results.map((row)=>present(request,row))})}
async function saveProduct(request,env,id=null){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const checked=validateProduct(body);if(checked.error)return error(checked.error);const p=checked.product;try{if(id){const result=await env.DB.prepare(`UPDATE products SET reference=COALESCE(NULLIF(?,''),reference),name=?,category=?,set_name=?,card_number=?,language=?,condition=?,notes=?,price=?,quantity=?,status=?,front_image_url=?,back_image_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.quantity,p.status,p.frontImageUrl,p.backImageUrl,id).run();if(!result.meta.changes)return error("Product not found.",404);return json({id:Number(id),message:"Product updated."})}const reference=p.reference||formatReference(await nextReferenceNumber(env));const result=await env.DB.prepare(`INSERT INTO products (reference,name,category,set_name,card_number,language,condition,notes,price,quantity,status,front_image_url,back_image_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.quantity,p.status,p.frontImageUrl,p.backImageUrl).run();return json({id:result.meta.last_row_id,message:"Product created."},201)}catch(cause){if(String(cause).includes("UNIQUE"))return error("That reference is already in use.",409);throw cause}}
function encodeBase64(buffer){const bytes=new Uint8Array(buffer),chunk=0x8000,parts=[];for(let index=0;index<bytes.length;index+=chunk)parts.push(String.fromCharCode(...bytes.subarray(index,index+chunk)));return btoa(parts.join(""))}
async function uploadImage(request,env){if(!env.GITHUB_TOKEN)return error("GitHub image upload is not configured.",503);const form=await request.formData(),file=form.get("image"),reference=clean(form.get("reference"),30).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")||"product",side=clean(form.get("side"),10)==="back"?"back":"front";if(!(file instanceof File)||!file.size)return error("Choose an image to upload.");if(file.size>4*1024*1024)return error("Image must be 4 MB or smaller.",413);const extensions={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"},extension=extensions[file.type];if(!extension)return error("Use a JPG, PNG or WebP image.",415);const repository=clean(env.GITHUB_REPOSITORY||"kollectozam/kollectozamkollectables",200),branch=clean(env.GITHUB_BRANCH||"main",100),filename=`${side}-${Date.now()}-${crypto.randomUUID().slice(0,8)}.${extension}`,path=`frontend/assets/img/products/${reference}/${filename}`,endpoint=`https://api.github.com/repos/${repository}/contents/${path}`;const response=await fetch(endpoint,{method:"PUT",headers:{"authorization":`Bearer ${env.GITHUB_TOKEN}`,"accept":"application/vnd.github+json","content-type":"application/json","user-agent":"kollectozam-admin","x-github-api-version":"2022-11-28"},body:JSON.stringify({message:`Add ${reference} ${side} product image`,content:encodeBase64(await file.arrayBuffer()),branch})});const result=await response.json().catch(()=>({}));if(!response.ok){console.error("GitHub upload failed",response.status,result?.message);return error(response.status===401||response.status===403?"GitHub upload permission was rejected.":"Photograph upload failed.",502)}return json({url:result.content?.download_url,path:result.content?.path},201)}
const IMAGE_TYPES={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
const githubConfig=(env)=>({repository:clean(env.GITHUB_REPOSITORY||"kollectozam/kollectozamkollectables",200),branch:clean(env.GITHUB_BRANCH||"main",100)});
async function github(env,method,path,body){const {repository}=githubConfig(env);const response=await fetch(`https://api.github.com/repos/${repository}${path}`,{method,headers:{"authorization":`Bearer ${env.GITHUB_TOKEN}`,"accept":"application/vnd.github+json","content-type":"application/json","user-agent":"kollectozam-admin","x-github-api-version":"2022-11-28"},body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({}));if(!response.ok){console.error("GitHub request failed",method,path,response.status,result?.message);const failure=new Error(response.status===401||response.status===403?"GitHub upload permission was rejected.":"Photograph upload failed.");failure.status=502;throw failure}return result}
// All photographs in a batch go into one commit, so Cloudflare rebuilds once per batch rather than once per image.
async function commitImages(env,files,message){const {repository,branch}=githubConfig(env);const ref=await github(env,"GET",`/git/ref/heads/${branch}`);const parent=ref.object.sha;const parentCommit=await github(env,"GET",`/git/commits/${parent}`);const tree=[];for(const file of files){const blob=await github(env,"POST","/git/blobs",{content:file.base64,encoding:"base64"});tree.push({path:file.path,mode:"100644",type:"blob",sha:blob.sha})}const newTree=await github(env,"POST","/git/trees",{base_tree:parentCommit.tree.sha,tree});const commit=await github(env,"POST","/git/commits",{message,tree:newTree.sha,parents:[parent]});await github(env,"PATCH",`/git/refs/heads/${branch}`,{sha:commit.sha});return (path)=>`https://raw.githubusercontent.com/${repository}/${branch}/${path}`}
const BATCH_LIMIT=10,MAX_IMAGE_BASE64=Math.ceil(4*1024*1024*4/3);
function batchImage(input,reference,side){if(!input)return null;const extension=IMAGE_TYPES[input.type],base64=String(input.data||"");if(!extension)return {error:"Use a JPG, PNG or WebP image."};if(!base64||base64.length>MAX_IMAGE_BASE64||!/^[A-Za-z0-9+/]+=*$/.test(base64))return {error:"Each photograph must be a valid image of 4 MB or smaller."};return {path:`frontend/assets/img/products/${reference.toLowerCase()}/${side}-${Date.now()}-${crypto.randomUUID().slice(0,8)}.${extension}`,base64}}
async function createBatch(request,env){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const items=Array.isArray(body.items)?body.items:[];if(!items.length)return error("Add at least one card.");if(items.length>BATCH_LIMIT)return error(`Send at most ${BATCH_LIMIT} cards per request.`);const status=["draft","available"].includes(body.status)?body.status:"draft";const prepared=[];let number=await nextReferenceNumber(env);for(const [index,item] of items.entries()){const checked=validateProduct({...item,category:item.category||"Singles",status,reference:"",frontImageUrl:"",backImageUrl:""});if(checked.error)return error(`Card ${index+1}: ${checked.error}`);const reference=formatReference(number++);const front=batchImage(item.front,reference,"front"),back=batchImage(item.back,reference,"back");for(const image of [front,back])if(image?.error)return error(`Card ${index+1}: ${image.error}`);prepared.push({product:{...checked.product,reference},front,back,lang:clean(item.lang,10),setId:clean(item.setId,40)})}const files=prepared.flatMap(({front,back})=>[front,back].filter(Boolean));let urlFor=null;if(files.length){if(!env.GITHUB_TOKEN)return error("GitHub image upload is not configured.",503);urlFor=await commitImages(env,files,`Add photographs for ${prepared[0].product.reference}${prepared.length>1?`–${prepared.at(-1).product.reference}`:""}`)}const statements=prepared.map(({product:p,front,back})=>env.DB.prepare(`INSERT INTO products (reference,name,category,set_name,card_number,language,condition,notes,price,quantity,status,front_image_url,back_image_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.reference,p.name,p.category,p.setName,p.cardNumber,p.language,p.condition,p.notes,p.price,p.quantity,p.status,front?urlFor(front.path):null,back?urlFor(back.path):null));const remembered=new Map();prepared.forEach(({product,lang,setId})=>{if(lang&&setId&&product.setName)remembered.set(`${lang}|${setId}`,[lang,setId,product.setName])});remembered.forEach((values)=>statements.push(env.DB.prepare("INSERT INTO set_names (lang,set_id,display_name) VALUES (?,?,?) ON CONFLICT(lang,set_id) DO UPDATE SET display_name=excluded.display_name,updated_at=CURRENT_TIMESTAMP").bind(...values)));await env.DB.batch(statements);return json({created:prepared.length,references:prepared.map(({product})=>product.reference),message:`${prepared.length} ${prepared.length===1?"card":"cards"} added.`},201)}
async function bulkStatus(request,env){let body;try{body=await request.json()}catch{return error("Invalid JSON body.")}const ids=[...new Set((Array.isArray(body.ids)?body.ids:[]).map(Number).filter((id)=>Number.isInteger(id)&&id>0))].slice(0,200),status=clean(body.status,20).toLowerCase();if(!ids.length)return error("Select at least one product.");if(!["draft","available","claimed","sold","archived"].includes(status))return error("Invalid inventory status.");const result=await env.DB.prepare(`UPDATE products SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id IN (${ids.map(()=>"?").join(",")})`).bind(status,...ids).run();return json({updated:result.meta.changes,message:`${result.meta.changes} updated.`})}
// Simplified Chinese lookups go through the server so the PikaQian key stays secret; results are cached in D1 so the monthly quota lasts.
const PIKAQIAN="https://api.pikaqian.com/v1",CN_SETS_TTL=7*24*60*60,CN_CARDS_TTL=30*24*60*60;
async function pikaqianAll(env,path){const items=[],seen=new Set();let cursor="";for(let page=0;page<20;page++){const url=new URL(PIKAQIAN+path);url.searchParams.set("page_size","100");if(cursor)url.searchParams.set("cursor",cursor);const response=await fetch(url,{headers:{"X-API-Key":env.PIKAQIAN_API_KEY,"accept":"application/json"}});if(!response.ok){const failure=new Error(response.status===401||response.status===403?"PikaQian rejected the API key":response.status===429?"PikaQian lookup limit reached":`PikaQian lookup failed (${response.status})`);failure.status=502;throw failure}const body=await response.json(),rows=Array.isArray(body.data)?body.data:[];const fresh=rows.filter((row)=>!seen.has(String(row.id)));fresh.forEach((row)=>seen.add(String(row.id)));items.push(...fresh);cursor=body.pagination?.next_cursor||"";if(!cursor||!fresh.length)break}return items}
async function cached(env,key,ttl,load){const row=await env.DB.prepare("SELECT body, fetched_at AS fetchedAt FROM lookup_cache WHERE key=?").bind(key).first();if(row&&Date.now()/1000-Number(row.fetchedAt)<ttl)return JSON.parse(row.body);try{const data=await load();await env.DB.prepare("INSERT INTO lookup_cache (key, body, fetched_at) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET body=excluded.body, fetched_at=excluded.fetched_at").bind(key,JSON.stringify(data),Math.floor(Date.now()/1000)).run();return data}catch(cause){if(row)return JSON.parse(row.body);throw cause}}
// Shaped like TCGdex (oldest set first, cards with localId) so quick add treats both sources the same way.
const cnSetList=(env)=>cached(env,"pikaqian:sets",CN_SETS_TTL,async()=>(await pikaqianAll(env,"/sets")).map((set)=>({id:String(set.id),name:set.local_name||set.name||String(set.id),english:set.name||"",releaseDate:set.release_date||"",cardCount:{official:Number(set.card_count?.official??set.card_count?.actual)||0}})).sort((a,b)=>String(a.releaseDate).localeCompare(String(b.releaseDate))));
async function cnSets(env){if(!env.PIKAQIAN_API_KEY)return error("PIKAQIAN_API_KEY is not configured",503);return json(await cnSetList(env))}
async function cnSet(env,setId){if(!env.PIKAQIAN_API_KEY)return error("PIKAQIAN_API_KEY is not configured",503);const id=setId.toLowerCase(),set=(await cnSetList(env)).find((entry)=>entry.id.toLowerCase()===id);if(!set)return error("Unknown set.",404);const cards=await cached(env,`pikaqian:cards:${id}`,CN_CARDS_TTL,async()=>{const numbers=new Set();return (await pikaqianAll(env,`/cards?set_id=${encodeURIComponent(set.id)}`)).filter((card)=>!card.is_variant).map((card)=>({localId:String(card.card_number??card.number??""),id:String(card.id),name:card.name||card.local_name||"",rarity:card.rarity||"",imageUrl:card.image_url||""})).filter((card)=>card.localId&&!numbers.has(card.localId)&&numbers.add(card.localId))});return json({...set,cards})}
// TCGGO currently has Japanese M6a while TCGdex's live Japanese API does not. Keep this a narrow,
// cached fallback so the rest of the catalogue is not coupled to a second provider.
const TCGGO_HOST="cardmarket-api-tcg.p.rapidapi.com",TCGGO_M6A_EPISODE="448",TCGGO_TTL=24*60*60;
function tcggoEnglishName(name){const text=clean(name,120),match=text.match(/\(([^()]+)\)\s*$/);return match?match[1].trim():/^[\x00-\x7F]+$/.test(text)?text:""}
async function tcggoM6aCards(env){
  if(!env.TCGGO_API_KEY){const failure=new Error("Japanese 30th Celebration lookup is not configured yet");failure.status=503;throw failure}
  return cached(env,"tcggo:m6a",TCGGO_TTL,async()=>{
    const cards=[],seen=new Set();
    for(let page=1;page<=10;page++){
      const url=new URL(`https://${TCGGO_HOST}/pokemon/episodes/${TCGGO_M6A_EPISODE}/cards`);
      url.searchParams.set("page",String(page));url.searchParams.set("per_page","50");url.searchParams.set("sort","card_number_lowest");
      const response=await fetch(url,{headers:{"X-RapidAPI-Key":env.TCGGO_API_KEY,"X-RapidAPI-Host":TCGGO_HOST,"accept":"application/json"}});
      if(!response.ok){const failure=new Error(response.status===401||response.status===403?"TCGGO rejected the API key":response.status===429?"TCGGO lookup limit reached":`TCGGO lookup failed (${response.status})`);failure.status=502;throw failure}
      const body=await response.json(),rows=Array.isArray(body.data)?body.data:[];
      for(const card of rows){const id=String(card.id??""),localId=String(card.card_number??"");if(!id||!localId||seen.has(id))continue;seen.add(id);cards.push({id:`tcggo-${id}`,localId,name:clean(card.name,120),englishName:tcggoEnglishName(card.name),rarity:clean(card.rarity,60),imageUrl:validImageUrl(card.image),provider:"tcggo"})}
      const total=Number(body.results)||0;if(!rows.length||(total&&cards.length>=total)||rows.length<50)break;
    }
    if(!cards.length){const failure=new Error("TCGGO returned no Japanese 30th Celebration cards");failure.status=502;throw failure}
    return cards;
  });
}
async function tcggoM6aSet(env){try{const cards=await tcggoM6aCards(env);return json({id:"M6a",name:"30th Celebration (Japanese)",english:"30th Celebration",provider:"tcggo",cardCount:{official:103,total:cards.length},cards})}catch(cause){return error(cause.message,cause.status||502)}}
async function setNames(env){const result=await env.DB.prepare("SELECT lang, set_id AS setId, display_name AS displayName FROM set_names ORDER BY updated_at DESC").all();return json({setNames:result.results})}
export async function onRequest(context){const {request,env,params}=context;try{const path=Array.isArray(params.path)?params.path.join("/"):String(params.path||"");if(request.method==="GET"&&path==="health")return json({ok:true,databaseBound:Boolean(env.DB)});if(request.method==="POST"&&path==="admin/login")return login(request,env);if(request.method==="POST"&&path==="admin/logout"){if(!sameOrigin(request))return error("Invalid logout request.",403);return logout()}if(request.method==="GET"&&path==="products"){if(!env.DB)return error("D1 binding DB is missing.",503);await ensureSchema(env);return publicProducts(request,env)}if(!path.startsWith("admin/"))return error("Not found.",404);if(!await hasAdminSession(request,env))return error("Administrator sign-in required.",401);if(request.method!=="GET"&&!sameOrigin(request))return error("Invalid administrator request.",403);if(!env.DB)return error("D1 binding DB is missing.",503);await ensureSchema(env);if(request.method==="GET"&&path==="admin/session")return json({authenticated:true,adminName:"Administrator"});if(request.method==="GET"&&path==="admin/products")return adminProducts(request,env);if(request.method==="POST"&&path==="admin/products")return saveProduct(request,env);if(request.method==="POST"&&path==="admin/images")return uploadImage(request,env);if(request.method==="POST"&&path==="admin/batch")return createBatch(request,env);if(request.method==="POST"&&path==="admin/products/status")return bulkStatus(request,env);if(request.method==="GET"&&path==="admin/set-names")return setNames(env);if(request.method==="GET"&&path==="admin/cn/sets")return await cnSets(env);const cnMatch=path.match(/^admin\/cn\/sets\/([A-Za-z0-9.-]{1,40})$/);if(cnMatch&&request.method==="GET")return await cnSet(env,cnMatch[1]);if(request.method==="GET"&&path.toLowerCase()==="admin/tcggo/sets/m6a")return await tcggoM6aSet(env);const match=path.match(/^admin\/products\/(\d+)$/);if(match&&request.method==="PUT")return saveProduct(request,env,match[1]);if(match&&request.method==="DELETE"){const result=await env.DB.prepare("UPDATE products SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(match[1]).run();return result.meta.changes?json({message:"Product archived."}):error("Product not found.",404)}return error("Not found.",404)}catch(cause){console.error(cause);if(cause?.status===502||cause?.status===503)return error(cause.message,cause.status);const message=String(cause&&cause.message||cause||"");return error(message.includes("no such table")?"The D1 products table has not been created.":message.includes("no such column")?"The D1 products table schema is outdated.":"Unexpected server error.",500)}}
